
environment:
  BOOST_ROOT: "C:\\Libraries\\boost_1_63_0"
  matrix:
  - VS_GEN: Visual Studio 14 2015
    CONFIG: RelWithDebInfo
    B_NAME: Win32
    BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_63_0\\lib32-msvc-14.0"
    CONFIGQGL: Release
    


matrix:
  fast_finish: true

# Operating system (build VM template)
os: Visual Studio 2015
branches:
  except:
  - coverity_scan
skip_tags: true



# scripts that are called at very beginning, before repo cloning
init:
  # Print environment info
  - set
  - msbuild /version
  - cmake --version
  - set PATH=%QTDIR%\bin;%PATH%




# scripts that run after cloning repository
install:

before_build:
  # install zlib
  - cmd: mkdir c:\zlib
  - appveyor DownloadFile "https://github.com/madler/zlib/archive/v1.2.9.zip" -FileName zlib.zip
  - 7z x zlib.zip -oC:\zlib
  - cmd: cd C:\zlib
  - cmd: mkdir C:\zlib-install
  - cmd: mkdir C:\zlib-build
  - cmd: cd C:\zlib-build
  - cmd: dir C:\zlib
  - cmake -G"%VS_GEN%" -DCMAKE_BUILD_TYPE=%CONFIG%  -DCMAKE_INSTALL_PREFIX:PATH=c:\zlib-install C:\zlib\zlib-1.2.9
  - msbuild zlib.sln /m
  - cmd: msbuild INSTALL.vcxproj
  - git clone -q --branch=master https://github.com/DGtal-team/DGtal.git C:\projects\dgtal
  - cd C:\projects\dgtal
  - cmake -Wno-dev -G"%VS_GEN%" -DCMAKE_BUILD_TYPE=%CONFIG%  -DBUILD_TESTING:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=FALSE  -DBOOST_ROOT=%BOOST_ROOT% -DZLIB_LIBRARY=c:/zlib-install/lib/zlibd.lib -DZLIB_INCLUDE_DIR=c:/zlib-install/include/ -DCAIRO_INCLUDE_DIRS=%APPVEYOR_BUILD_FOLDER%\Appveyor\include -DCAIRO_LIBRAIRIES=%APPVEYOR_BUILD_FOLDER%\Appveyor\lib\x86\cairo.lib -DWITH_CAIRO=ON .
  - msbuild /m /p:Configuration=%CONFIG% /p:Platform=%B_NAME% DGtal.sln 
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake -Wno-dev -G"%VS_GEN%" -DCMAKE_BUILD_TYPE=%CONFIG%   -DBOOST_ROOT=%BOOST_ROOT%   -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DCMAKE_INSTALL_PREFIX:PATH=c:\zlib-install C:\zlib\zlib-1.2.9 -DDGtal_DIR=C:\projects\dgtal -DCAIRO_INCLUDE_DIRS=%APPVEYOR_BUILD_FOLDER%\Appveyor\include -DCAIRO_LIBRAIRIES=%APPVEYOR_BUILD_FOLDER%\Appveyor\lib\x86\cairo.lib  .


build_script:
  - echo %CONFIG%
  - msbuild /m /p:Configuration=%CONFIG% /p:Platform=%B_NAME% GTVimageVect.sln 

test: off
deploy: off